project:
  type: website 
  output-dir: docs

website:
  title: "My website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Information 
        href: information.qmd
      - text: Hobby
        href: hobby.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

